---
title: "CSE 6242 Assignment 3"
author: Vincent La (Georgia Tech ID - vla6)
date: October 21, 2017
output:
  pdf_document:
    pandoc_args: [
  "--output=hw3.pdf"
    ]
---

```{r loading, echo=FALSE, results='hide', message=FALSE}
# Assignment 3: http://cse6242.gatech.edu/fall-2017/hw3/
# To compile R Markdown in terminal run: Rscript -e "rmarkdown::render('hw3.Rmd', clean=TRUE)"
# To create zip file: zip hw3.zip hw3.Rmd hw3_report.pdf

require(ggplot2)
require(GGally)
```

# Question 1: Data Preprocessing

```{r preprocessing, eval = FALSE, echo = FALSE}
train = read.csv('./mnist/mnist_train.csv', header=FALSE)
test = read.csv('./mnist/mnist_test.csv', header=FALSE)

last_row = nrow(train)

train_0_1_cols = c()
train_3_5_cols = c()
for (i in 1:ncol(train)){
  if (train[last_row, i] == 0 | train[last_row, i] == 1){
    train_0_1_cols = c(train_0_1_cols, colnames(train)[i])
  } else if (train[last_row, i] == 3 | train[last_row, i] == 5){
    train_3_5_cols = c(train_3_5_cols, colnames(train[i]))
  }
}

test_0_1_cols = c()
test_3_5_cols = c()
for (i in 1:ncol(test)){
  if (test[last_row, i] == 0 | test[last_row, i] == 1){
    test_0_1_cols = c(test_0_1_cols, colnames(test)[i])
  } else if (test[last_row, i] == 3 | test[last_row, i] == 5){
    test_3_5_cols = c(test_3_5_cols, colnames(test[i]))
  }
}

train_0_1 = train[train_0_1_cols]
train_3_5 = train[train_3_5_cols]
test_0_1 = test[test_0_1_cols]
test_3_5 = test[test_3_5_cols]

print(dim(train_0_1))
print(dim(train_3_5))
print(dim(test_0_1))
print(dim(test_3_5))

# Removing true image labels
train_labels_0_1 = train_0_1[last_row, ]
test_labels_0_1 = test_0_1[last_row, ]
train_labels_3_5 = train_3_5[last_row, ]
test_labels_3_5 = test_3_5[last_row, ]

# Deleting the image labels from DF
train_0_1 = train_0_1[-c(last_row), ]
test_0_1 = test_0_1[-c(last_row), ]
train_3_5 = train_3_5[-c(last_row), ]
test_3_5 = test_3_5[-c(last_row), ]
```

```{r preprocessing_viz, eval = FALSE, echo = FALSE}
ex_0_matrix = matrix(train_0_1[, 'V1'], nrow=28, ncol=28)
ex_1_matrix = matrix(train_0_1[, 'V12664'], nrow=28, ncol=28)
ex_3_matrix = matrix(train_3_5[, 'V12666'], nrow=28, ncol=28)
ex_5_matrix = matrix(train_3_5[, 'V24217'], nrow=28, ncol=28)

# Taken from https://www.r-bloggers.com/creating-an-image-of-a-matrix-in-r-using-image/
rotate <- function(x) t(apply(x, 2, rev))
image(rotate(ex_0_matrix))
image(rotate(ex_1_matrix))
image(rotate(ex_3_matrix))
image(rotate(ex_5_matrix))
```

# Theory




